config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/leetdx/argocd-example-apps
      targetRevision: main

applications:
  - name: guestbook
  - name: helm-guestbook
  - name: sync-waves
